<a href="https://colab.research.google.com/github/PalomiBollapalli/B19_1233/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
fp=open("example.txt","w")
fp.write("Hello,B.Tech students!\n")
fp.write("sR university\n")
fp.write("Palomi\n")
fp.close()
print("data written successfully!")

data written successfully!


In [12]:
file=open("example.txt","r")
content=file.read()
print("file content:\n",content)
file.close()

file content:
 Hello,B.Tech students!
sR university
Palomi



In [15]:
file=open("example.txt","r")
line1=file.readline()
line2=file.readline()
line3=file.readline()
print("first line:",line1)
print("second line:",line2)
print("third line:",line3)
file.close()

first line: Hello,B.Tech students!

second line: sR university

third line: Palomi



In [16]:
file=open("example.txt","r")
lines=file.readlines()
print("all lines:",lines)
file.close()

all lines: ['Hello,B.Tech students!\n', 'sR university\n', 'Palomi\n']


In [17]:
file=open("example.txt","a")
file.write("appending new data\n")
file.close()

In [18]:
with open("example.txt","r") as fp:
  data=fp.read()
  print(data)

Hello,B.Tech students!
sR university
Palomi
appending new data



In [21]:
import csv
with open("data.csv","w",newline='') as fp:
  wr=csv.writer(fp)
  wr.writerows([["name","age","course"],["aaa",21,"cse"],["bbb",20,"ece"]])
with open("data.csv","r") as file:
  re=csv.reader(file)
  for row in re:
    print(row)

['name', 'age', 'course']
['aaa', '21', 'cse']
['bbb', '20', 'ece']


In [22]:
import numpy as np
arr1=np.array([1,2,3,4])
print("1d array:",arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print("2d array:\n",arr2)
zeros_arr=np.zeros((3,3))
print("zeros array:\n",zeros_arr)
range_arr=np.arrange(0,10,2)
ones_arr=np.ones((2,2))
print("range array:",range_arr)
rand_arr=np.random.rand(2,3)
print("random array:\n",rand_arr)

1d array: [1 2 3 4]
2d array:
 [[1 2 3]
 [4 5 6]]
zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


AttributeError: module 'numpy' has no attribute 'arrange'

In [23]:
arr=np.array([[1,2,3],[4,5,6]])
print("array:\n",arr)
print("shape:",arr.shape)
print("item size:",arr.itemsize)
print("data type:",arr.dtype)

array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3)
item size: 8
data type: int64


In [24]:
a=np.array([10,20,30,40,50])
print("first element:",a[0])
print("last element:",a[-1])
print("slice[1:4]:",a[1:4])
print("every second element:",a[::2])

first element: 10
last element: 50
slice[1:4]: [20 30 40]
every second element: [10 30 50]


In [25]:
#2D indexing
arr2=np.array([[1,2,3],[4,5,6]])
print("element at r1 col 2:",arr2[0,1])
print("second row",arr2[1,:])
print("second column:",arr2[:,1])

element at r1 col 2: 2
second row [4 5 6]
second column: [2 5]


In [28]:
arr=np.array([[1,2,3],[4,5,6]])
print("sum:",np.sum(arr))
print("max:",np.max(arr))
print("min:",np.min(arr))
print("mean:",np.mean(arr))
print("median:",np.median(arr))
print("standar deviation:",np.std(arr))
print("sum along axis 0:",np.sum(arr,axis=0))
print("sum along axis 1:",np.sum(arr,axis=1))

sum: 21
max: 6
min: 1
mean: 3.5
median: 3.5
standar deviation: 1.707825127659933
sum along axis 0: [5 7 9]
sum along axis 1: [ 6 15]


In [29]:
import numpy as np
marks = np.array([
    [85, 90, 88],
    [78, 81, 85],
    [92, 89, 95]
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))
import numpy as np
marks = np.array([
    [85, 90, 88],
    [78, 81, 85],
    [92, 89, 95]
])
print("Average marks per student:", np.mean(marks, axis=1))
print("Average marks per subject:", np.mean(marks, axis=0))
print("Highest marks in each subject:", np.max(marks, axis=0))
print("Lowest marks in each subject:", np.min(marks, axis=0))

Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
Average marks per student: [87.66666667 81.33333333 92.        ]
Average marks per subject: [85.         86.66666667 89.33333333]
Highest marks in each subject: [92 90 95]
Lowest marks in each subject: [78 81 85]
